In [1]:
!pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.14.5-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Requirement already satisfied: numpy<3,>=1.22.3 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from statsmodels) (1.26.4)
Collecting scipy!=1.9.2,>=1.8 (from statsmodels)
  Downloading scipy-1.16.3-cp312-cp312-win_amd64.whl.metadata (60 kB)
Requirement already satisfied: pandas!=2.1.0,>=1.4 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from statsmodels) (2.2.2)
Collecting patsy>=0.5.6 (from statsmodels)
  Using cached patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: packaging>=21.3 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from statsmodels) (24.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from pandas!=2.1.0,>=1.4->statsmodels) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0,>=1.4->statsmodels) (1.16.0)
Downloading statsmodels-0.14.5-cp312-cp312-win_amd64.whl (9.6 MB)
   ---------------------------------------- 0.0/9.6 MB ? eta -:--:--
   --------------- ------------------------ 3.7/9.6 MB 21.7 MB/s eta 0:00:01
   ----------------- ---------------------- 4.2/9.6 MB 16.7 MB/s eta 0:00:01
   ---------------------- ----------------- 5.5/9.6 MB 8.8 MB/s eta 0:00:01
   --------------------------- ------------ 6.6/9.6 MB 8.4 MB/s eta 0:00:01
   ------------------------------ --------- 7.3/9.6 MB 6.9 MB/s eta 0:00:01
   -------------------------------- ------- 7.9/9.6 MB 6.6 MB/s eta 0:00:01
   ------------------------------------- -- 8.9/9.6 MB 5.9 MB/s eta 0:00:01
   ---------------------------------------- 9.6/9.6 MB 5.8 MB/s eta 0:00:00
Using cached patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Downloading scipy-1.16.3-cp312-cp312-win_amd64.whl (38.6 MB)
   ---------------------------------------- 0.0/38.6 MB ? eta -:--:--
   - -------------------------------------- 1.3/38.6 MB 6.7 MB/s eta 0:00:06
   -- ------------------------------------- 2.1/38.6 MB 5.6 MB/s eta 0:00:07
   -- ------------------------------------- 2.9/38.6 MB 4.7 MB/s eta 0:00:08
   ---- ----------------------------------- 3.9/38.6 MB 4.6 MB/s eta 0:00:08
   ----- ---------------------------------- 5.2/38.6 MB 5.0 MB/s eta 0:00:07
   ------- -------------------------------- 7.1/38.6 MB 5.6 MB/s eta 0:00:06
   -------- ------------------------------- 7.9/38.6 MB 5.4 MB/s eta 0:00:06
   -------- ------------------------------- 8.4/38.6 MB 5.0 MB/s eta 0:00:06
   --------- ------------------------------ 8.9/38.6 MB 4.7 MB/s eta 0:00:07
   ---------- ----------------------------- 9.7/38.6 MB 4.6 MB/s eta 0:00:07
   ----------- ---------------------------- 10.7/38.6 MB 4.6 MB/s eta 0:00:07
   ------------ --------------------------- 12.3/38.6 MB 4.8 MB/s eta 0:00:06
   -------------- ------------------------- 14.2/38.6 MB 5.1 MB/s eta 0:00:05
   ---------------- ----------------------- 15.7/38.6 MB 5.2 MB/s eta 0:00:05
   ---------------- ----------------------- 16.3/38.6 MB 5.1 MB/s eta 0:00:05
   ----------------- ---------------------- 16.8/38.6 MB 5.0 MB/s eta 0:00:05
   ------------------ --------------------- 17.6/38.6 MB 4.9 MB/s eta 0:00:05
   ------------------- -------------------- 18.9/38.6 MB 4.9 MB/s eta 0:00:05
   -------------------- ------------------- 19.9/38.6 MB 4.9 MB/s eta 0:00:04
   --------------------- ------------------ 21.0/38.6 MB 4.9 MB/s eta 0:00:04
   ---------------------- ----------------- 21.5/38.6 MB 4.8 MB/s eta 0:00:04
   ----------------------- ---------------- 22.3/38.6 MB 4.8 MB/s eta 0:00:04
   ------------------------ --------------- 23.3/38.6 MB 4.8 MB/s eta 0:00:04
   ------------------------- -------------- 24.9/38.6 MB 4.9 MB/s eta 0:00:03
   --------------------------- ------------ 26.5/38.6 MB 4.9 MB/s eta 0:00:03
   ---------------------------- ----------- 27.3/38.6 MB 5.0 MB/s eta 0:00:03
   ---------------------------- ----------- 27.8/38.6 MB 4.8 MB/s eta 0:00:03
   ----------------------------- ---------- 28.3/38.6 MB 4.8 MB/s eta 0:00:03
   ------------------------------ --------- 29.4/38.6 MB 4.8 MB/s eta 0:00:02
   -------------------------------- ------- 30.9/38.6 MB 4.8 MB/s eta 0:00:02
   --------------------------------- ------ 32.2/38.6 MB 4.9 MB/s eta 0:00:02
   ----------------------------------- ---- 34.1/38.6 MB 5.0 MB/s eta 0:00:01
   ------------------------------------ --- 35.1/38.6 MB 5.0 MB/s eta 0:00:01
   ------------------------------------ --- 35.7/38.6 MB 5.0 MB/s eta 0:00:01
   ------------------------------------- -- 36.2/38.6 MB 4.9 MB/s eta 0:00:01
   -------------------------------------- - 37.0/38.6 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------  37.7/38.6 MB 4.8 MB/s eta 0:00:01
   ---------------------------------------- 38.6/38.6 MB 4.8 MB/s eta 0:00:00
Installing collected packages: scipy, patsy, statsmodels
Successfully installed patsy-1.0.2 scipy-1.16.3 statsmodels-0.14.5

In [3]:
! pip install seaborn

Collecting seaborn
  Using cached seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=1.2 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from seaborn) (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from pandas>=1.2->seaborn) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\jeet\.conda\envs\ctrextension\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.16.0)
Using cached seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

## Setting the path to input files

In [12]:
import os
from singscore.singscore import *

BASE_DIR = os.getcwd()   # current working directory
print(BASE_DIR)

entrez_sample_path = os.path.normpath('{}/{}'.format(BASE_DIR,
                                'singscore/test/test_data/entrez_sample.txt'))

sig_path = os.path.normpath('{}/{}'.format(BASE_DIR,
                                'singscore/test/test_sigs/tgfb_upDown.txt'))

d:\GS\PySingscore_replicate

## Reading the data

In [5]:
data = pandas.read_csv(open(entrez_sample_path, 'r'), header=
'infer', sep='\t')
data = data.set_index(keys='EntrezID')
data

,D_Ctrl_R1,D_TGFb_R1,D_Ctrl_R2,D_TGFb_R2,Hes_Ctrl_R1,Hes_TGFb_R1,Hes_Ctrl_R2,Hes_TGFb_R2,Hil_Ctrl_R1,Hil_Ctrl_R2
EntrezID,,,,,,,,,,
2,4.449761,4.536331,4.600037,4.515623,4.550698,4.681318,4.434600,4.462480,4.440943,4.516277
9,7.209661,7.643405,7.115128,7.343871,7.002150,7.508886,7.432266,7.390676,7.026492,7.516390
10,4.759523,4.692182,4.651241,4.700832,4.798863,4.722866,4.676497,4.600500,4.671553,4.797493
12,6.605422,5.630332,7.130885,6.432135,5.774363,6.668610,5.973094,7.382852,6.328466,6.328010
13,5.484495,5.591267,5.450615,5.510995,5.481345,5.372441,5.372441,5.794506,5.571761,5.361441
...,...,...,...,...,...,...,...,...,...,...
727897,5.662754,5.445969,5.433057,5.159152,5.695544,5.665951,4.747162,5.525359,5.510900,5.345197
728215,4.562833,5.060502,4.665515,5.077294,5.199263,4.770554,4.759490,4.603406,4.438098,4.724390
728621,3.887105,3.967852,3.999327,3.986190,3.904852,4.057919,3.886360,4.000872,3.980695,3.822199
729164,5.550880,5.295511,5.173193,5.182718,5.391617,5.096315,5.466387,5.251477,5.319442,5.078190
752014,5.517907,5.215606,5.121201,5.107979,5.191096,5.337286,5.099750,5.263531,5.219676,5.158507

# prepare signatures

### seperating the aanotated up and downregulated genes

In [6]:
sigs = pandas.read_csv(open(sig_path, 'r'), header=
'infer', sep='\t')
sigs

,EntrezID,Symbol,upDown_integrative_signature,upDown_comparative_signature,upDown
0,19,ABCA1,0,up,up
1,87,ACTN1,0,up,up
2,136,ADORA2B,0,down,down
3,182,JAG1,up,up,up
4,220,ALDH1A3,down,0,down
...,...,...,...,...,...
296,161291,TMEM30B,down,0,down
297,221749,C6orf145,0,up,up
298,347902,AMIGO2,0,up,up
299,389136,VGLL3,up,0,up
300,402055,SRRD,0,up,up

In [7]:
# subset the data for up and down
up = sigs[sigs['upDown'] == 'up']
down = sigs[sigs['upDown'] == 'down']
up

,EntrezID,Symbol,upDown_integrative_signature,upDown_comparative_signature,upDown
0,19,ABCA1,0,up,up
1,87,ACTN1,0,up,up
3,182,JAG1,up,up,up
6,241,ALOX5AP,up,up,up
8,323,APBB2,0,up,up
...,...,...,...,...,...
295,150094,SIK1,0,up,up
297,221749,C6orf145,0,up,up
298,347902,AMIGO2,0,up,up
299,389136,VGLL3,up,0,up
300,402055,SRRD,0,up,up

In [8]:
# get a list of ids
up = list(up['EntrezID'])
down = list(down['EntrezID'])
up

[19,
 87,
 182,
 241,
 323,
 406,
 649,
 650,
 659,
 669,
 800,
 860,
 966,
 1000,
 1009,
 1277,
 1281,
 1282,
 1284,
 1289,
 1290,
 1293,
 1294,
 1462,
 1490,
 1836,
 2004,
 2009,
 2048,
 2114,
 2200,
 2297,
 2335,
 2791,
 2887,
 3162,
 3269,
 3488,
 3490,
 3589,
 3624,
 3678,
 3690,
 3720,
 3725,
 3726,
 3772,
 3778,
 3918,
 4015,
 4060,
 4092,
 4094,
 4148,
 4237,
 4312,
 4313,
 4318,
 4319,
 4330,
 4616,
 4651,
 4688,
 4739,
 4824,
 4907,
 5054,
 5154,
 5218,
 5270,
 5293,
 5329,
 5420,
 5654,
 5708,
 5744,
 5796,
 5898,
 5999,
 6447,
 6498,
 6578,
 6583,
 6588,
 6591,
 6678,
 6695,
 6781,
 6876,
 6925,
 6926,
 7040,
 7041,
 7045,
 7052,
 7057,
 7077,
 7130,
 7145,
 7168,
 7171,
 7277,
 7286,
 7424,
 7431,
 7474,
 7846,
 7857,
 7980,
 8038,
 8091,
 8406,
 8407,
 8459,
 8460,
 8553,
 8609,
 8682,
 8728,
 8821,
 8877,
 8905,
 9244,
 9260,
 9267,
 9315,
 9540,
 9645,
 9732,
 9891,
 9902,
 9945,
 9953,
 9955,
 10000,
 10202,
 10272,
 10395,
 10398,
 10512,
 10631,
 10916,
 10979,
 11010,
 11015,
 11077,
 11099,
 11174,
 11221,
 22891,
 23002,
 23022,
 23023,
 23141,
 23180,
 26278,
 26499,
 26585,
 29931,
 29940,
 29995,
 50515,
 51083,
 51129,
 51313,
 51339,
 54908,
 55022,
 55323,
 55568,
 55584,
 55701,
 55738,
 56034,
 56675,
 56937,
 57007,
 64131,
 64750,
 79669,
 79899,
 80206,
 81029,
 81606,
 81631,
 85458,
 92689,
 129642,
 150094,
 221749,
 347902,
 389136,
 402055]

In [14]:
print(f'{len(up), len(down)}')

(193, 108)

In [16]:
up_present = [gene for gene in up if gene in data.index]
down_present = [gene for gene in down if gene in data.index]

# Print counts and summary
print(f"Total up genes in signature: {len(up)}")
print(f"Up genes found in expression data: {len(up_present)}")

print(f"Total down genes in signature: {len(down)}")
print(f"Down genes found in expression data: {len(down_present)}")

# Optionally, print the missing ones
missing_up = set(up) - set(data.index)
missing_down = set(down) - set(data.index)

print(f"Missing up genes: {len(missing_up)}")
print(f"Missing down genes: {len(missing_down)}")

Total up genes in signature: 193
Up genes found in expression data: 193
Total down genes in signature: 108
Down genes found in expression data: 108
Missing up genes: 0
Missing down genes: 0

# Scoring the genes

In [15]:
scored_data = score(up_gene=up, down_gene=down, sample=data,
                    norm_method='theoretical', full_data=True)
print(scored_data)

             up_score       mad_up  down_score     mad_down  total_score  \
D_Ctrl_R1    0.560964  3119.395068   -0.149062  2615.310313     0.411902
D_TGFb_R1    0.749316  2352.889721    0.037679  2083.056117     0.786994
D_Ctrl_R2    0.568412  3129.773283   -0.167377  2593.071280     0.401036
D_TGFb_R2    0.750357  2470.015296    0.020365  2287.655223     0.770722
Hes_Ctrl_R1  0.580465  3134.221090   -0.082550  2358.078829     0.497915
Hes_TGFb_R1  0.728940  2416.641616   -0.052818  2778.396557     0.676123
Hes_Ctrl_R2  0.588178  3138.668897   -0.071294  2262.450985     0.516884
Hes_TGFb_R2  0.738955  2324.720279   -0.050488  2585.658269     0.688467
Hil_Ctrl_R1  0.583143  3553.797518   -0.145134  2524.871578     0.438009
Hil_Ctrl_R2  0.574339  3396.641683   -0.139276  2521.906374     0.435063

               total_mad
D_Ctrl_R1    5734.705381
D_TGFb_R1    4435.945838
D_Ctrl_R2    5722.844563
D_TGFb_R2    4757.670519
Hes_Ctrl_R1  5492.299918
Hes_TGFb_R1  5195.038174
Hes_Ctrl_R2  5401.119882
Hes_TGFb_R2  4910.378548
Hil_Ctrl_R1  6078.669096
Hil_Ctrl_R2  5918.548056

In [19]:
# plot dispersion of scores
output_path = os.path.normpath('{}/{}'.format(BASE_DIR,
                                    'singscore/test/output_JN/dispersion.png'))

plotdispersion(scored_data, ctrlstring='Ctrl', teststring='TGFb',
               testlabel='TGFb', colour_1='g', colour_2='b',
               outpath=output_path, show=False)

In [17]:
output_path = os.path.normpath('{}/{}'.format(BASE_DIR,
                                        'singscore/test/output_JN/nulldist.png'))
permd = permutate(data, n_up=193, n_down=108)
pvals = empiricalpval(permutations=permd, score=scored_data)
print(pvals)

             empirical p value
D_Ctrl_R1             0.995600
D_TGFb_R1             0.000100
D_Ctrl_R2             0.997800
D_TGFb_R2             0.000100
Hes_Ctrl_R1           0.522848
Hes_TGFb_R1           0.000100
Hes_Ctrl_R2           0.305669
Hes_TGFb_R2           0.000100
Hil_Ctrl_R1           0.964704
Hil_Ctrl_R2           0.968903

In [18]:
nulldistribution(permutations=permd, score=scored_data, nrows=2, ncols=5,
                 threshold=0.05, outpath=output_path, show=False)

d:\GS\PySingscore_replicate\singscore\singscore.py:856: UserWarning:

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  # distribution plot
d:\GS\PySingscore_replicate\singscore\singscore.py:856: UserWarning:

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  # distribution plot
d:\GS\PySingscore_replicate\singscore\singscore.py:856: UserWarning:

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  # distribution plot
d:\GS\PySingscore_replicate\singscore\singscore.py:856: UserWarning:

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  # distribution plot
d:\GS\PySingscore_replicate\singscore\singscore.py:856: UserWarning:

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  # distribution plot
d:\GS\PySingscore_replicate\singscore\singscore.py:856: UserWarning:

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  # distribution plot
d:\GS\PySingscore_replicate\singscore\singscore.py:856: UserWarning:

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  # distribution plot
d:\GS\PySingscore_replicate\singscore\singscore.py:856: UserWarning:

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  # distribution plot
d:\GS\PySingscore_replicate\singscore\singscore.py:856: UserWarning:

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  # distribution plot
d:\GS\PySingscore_replicate\singscore\singscore.py:856: UserWarning:

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  # distribution plot